/**
 * 卖家端菜单数据（appType: 2）
 * 按照要求的7大模块结构：商品、订单、财务、营销、统计、设置、消息
 */
export const sellerMenus = [
  // ========== 1. 商品 (goods) ==========
  {
    id: 'seller-goods',
    title: '商品',
    name: 'seller-goods',
    path: '/seller/goods',
    level: 0,
    frontRoute: 'seller/goods',
    parentId: null,
    sortOrder: 1,
    permission: '',
    icon: 'shopping',
    description: '商品管理',
    type: 0,
    appType: 2,
  },
  // 商品管理
  {
    id: 'seller-goods-management',
    title: '商品管理',
    name: 'seller-goods-management',
    path: '/seller/goods/management',
    level: 1,
    frontRoute: 'seller/goods/management',
    parentId: 'seller-goods',
    sortOrder: 0,
    permission: '/seller/goods/management',
    icon: 'tool',
    description: '商品管理',
    type: 0,
    appType: 2,
  },
  {
    id: 'seller-goods-publish',
    title: '商品发布',
    name: 'seller-goods-publish',
    path: '/seller/goods/publish',
    level: 2,
    frontRoute: 'seller/goods/publish',
    parentId: 'seller-goods-management',
    sortOrder: 0,
    permission: '/seller/goods/publish',
    icon: 'plus-circle',
    description: '商品发布',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-goods-list',
    title: '商品列表',
    name: 'seller-goods-list',
    path: '/seller/goods/list',
    level: 2,
    frontRoute: 'seller/goods/list',
    parentId: 'seller-goods-management',
    sortOrder: 1,
    permission: '/seller/goods/list',
    icon: 'unordered-list',
    description: '商品列表',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-goods-template',
    title: '商品模板',
    name: 'seller-goods-template',
    path: '/seller/goods/template',
    level: 2,
    frontRoute: 'seller/goods/template',
    parentId: 'seller-goods-management',
    sortOrder: 2,
    permission: '/seller/goods/template',
    icon: 'file-text',
    description: '商品模板',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-goods-category',
    title: '店铺分类',
    name: 'seller-goods-category',
    path: '/seller/goods/category',
    level: 2,
    frontRoute: 'seller/goods/category',
    parentId: 'seller-goods-management',
    sortOrder: 3,
    permission: '/seller/goods/category',
    icon: 'folder-open',
    description: '店铺分类',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-goods-stock-warning',
    title: '库存预警',
    name: 'seller-goods-stock-warning',
    path: '/seller/goods/stock-warning',
    level: 2,
    frontRoute: 'seller/goods/stock-warning',
    parentId: 'seller-goods-management',
    sortOrder: 4,
    permission: '/seller/goods/stock-warning',
    icon: 'warning',
    description: '库存预警',
    type: 1,
    appType: 2,
  },

  // ========== 2. 订单 (order) ==========
  {
    id: 'seller-order',
    title: '订单',
    name: 'seller-order',
    path: '/seller/order',
    level: 0,
    frontRoute: 'seller/order',
    parentId: null,
    sortOrder: 2,
    permission: '',
    icon: 'shopping-cart',
    description: '订单管理',
    type: 0,
    appType: 2,
  },
  // 订单管理
  {
    id: 'seller-order-management',
    title: '订单管理',
    name: 'seller-order-management',
    path: '/seller/order/management',
    level: 1,
    frontRoute: 'seller/order/management',
    parentId: 'seller-order',
    sortOrder: 0,
    permission: '/seller/order/management',
    icon: 'ordered-list',
    description: '订单管理',
    type: 0,
    appType: 2,
  },
  {
    id: 'seller-order-goods',
    title: '商品订单',
    name: 'seller-order-goods',
    path: '/seller/order/goods',
    level: 2,
    frontRoute: 'seller/order/goods',
    parentId: 'seller-order-management',
    sortOrder: 0,
    permission: '/seller/order/goods',
    icon: 'shopping',
    description: '商品订单',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-order-virtual',
    title: '虚拟订单',
    name: 'seller-order-virtual',
    path: '/seller/order/virtual',
    level: 2,
    frontRoute: 'seller/order/virtual',
    parentId: 'seller-order-management',
    sortOrder: 1,
    permission: '/seller/order/virtual',
    icon: 'cloud',
    description: '虚拟订单',
    type: 1,
    appType: 2,
  },
  // 评价管理
  {
    id: 'seller-order-evaluation',
    title: '评价管理',
    name: 'seller-order-evaluation',
    path: '/seller/order/evaluation',
    level: 1,
    frontRoute: 'seller/order/evaluation',
    parentId: 'seller-order',
    sortOrder: 1,
    permission: '/seller/order/evaluation',
    icon: 'star',
    description: '评价管理',
    type: 0,
    appType: 2,
  },
  {
    id: 'seller-order-evaluation-manage',
    title: '评价管理',
    name: 'seller-order-evaluation-manage',
    path: '/seller/order/evaluation-manage',
    level: 2,
    frontRoute: 'seller/order/evaluation-manage',
    parentId: 'seller-order-evaluation',
    sortOrder: 0,
    permission: '/seller/order/evaluation-manage',
    icon: 'message',
    description: '评价管理',
    type: 1,
    appType: 2,
  },
  // 售后管理
  {
    id: 'seller-order-after-sale',
    title: '售后管理',
    name: 'seller-order-after-sale',
    path: '/seller/order/after-sale',
    level: 1,
    frontRoute: 'seller/order/after-sale',
    parentId: 'seller-order',
    sortOrder: 2,
    permission: '/seller/order/after-sale',
    icon: 'customer-service',
    description: '售后管理',
    type: 0,
    appType: 2,
  },
  {
    id: 'seller-order-return',
    title: '退货管理',
    name: 'seller-order-return',
    path: '/seller/order/return',
    level: 2,
    frontRoute: 'seller/order/return',
    parentId: 'seller-order-after-sale',
    sortOrder: 0,
    permission: '/seller/order/return',
    icon: 'rollback',
    description: '退货管理',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-order-refund',
    title: '退款管理',
    name: 'seller-order-refund',
    path: '/seller/order/refund',
    level: 2,
    frontRoute: 'seller/order/refund',
    parentId: 'seller-order-after-sale',
    sortOrder: 1,
    permission: '/seller/order/refund',
    icon: 'dollar',
    description: '退款管理',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-order-complaint',
    title: '投诉管理',
    name: 'seller-order-complaint',
    path: '/seller/order/complaint',
    level: 2,
    frontRoute: 'seller/order/complaint',
    parentId: 'seller-order-after-sale',
    sortOrder: 2,
    permission: '/seller/order/complaint',
    icon: 'exclamation-circle',
    description: '投诉管理',
    type: 1,
    appType: 2,
  },

  // ========== 3. 财务 (bill) ==========
  {
    id: 'seller-bill',
    title: '财务',
    name: 'seller-bill',
    path: '/seller/bill',
    level: 0,
    frontRoute: 'seller/bill',
    parentId: null,
    sortOrder: 3,
    permission: '',
    icon: 'dollar',
    description: '财务管理',
    type: 0,
    appType: 2,
  },
  // 财务管理
  {
    id: 'seller-bill-management',
    title: '财务管理',
    name: 'seller-bill-management',
    path: '/seller/bill/management',
    level: 1,
    frontRoute: 'seller/bill/management',
    parentId: 'seller-bill',
    sortOrder: 0,
    permission: '/seller/bill/management',
    icon: 'calculator',
    description: '财务管理',
    type: 0,
    appType: 2,
  },
  {
    id: 'seller-bill-reconciliation',
    title: '财务对账',
    name: 'seller-bill-reconciliation',
    path: '/seller/bill/reconciliation',
    level: 2,
    frontRoute: 'seller/bill/reconciliation',
    parentId: 'seller-bill-management',
    sortOrder: 0,
    permission: '/seller/bill/reconciliation',
    icon: 'file-excel',
    description: '财务对账',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-bill-settlement',
    title: '店铺结算',
    name: 'seller-bill-settlement',
    path: '/seller/bill/settlement',
    level: 2,
    frontRoute: 'seller/bill/settlement',
    parentId: 'seller-bill-management',
    sortOrder: 1,
    permission: '/seller/bill/settlement',
    icon: 'transaction',
    description: '店铺结算',
    type: 1,
    appType: 2,
  },
  // 发票管理
  {
    id: 'seller-bill-invoice',
    title: '发票管理',
    name: 'seller-bill-invoice',
    path: '/seller/bill/invoice',
    level: 1,
    frontRoute: 'seller/bill/invoice',
    parentId: 'seller-bill',
    sortOrder: 1,
    permission: '/seller/bill/invoice',
    icon: 'file-text',
    description: '发票管理',
    type: 0,
    appType: 2,
  },
  {
    id: 'seller-bill-invoice-manage',
    title: '发票管理',
    name: 'seller-bill-invoice-manage',
    path: '/seller/bill/invoice-manage',
    level: 2,
    frontRoute: 'seller/bill/invoice-manage',
    parentId: 'seller-bill-invoice',
    sortOrder: 0,
    permission: '/seller/bill/invoice-manage',
    icon: 'file-text',
    description: '发票管理',
    type: 1,
    appType: 2,
  },

  // ========== 4. 营销 (promotion) ==========
  {
    id: 'seller-promotion',
    title: '营销',
    name: 'seller-promotion',
    path: '/seller/promotion',
    level: 0,
    frontRoute: 'seller/promotion',
    parentId: null,
    sortOrder: 4,
    permission: '',
    icon: 'rocket',
    description: '营销管理',
    type: 0,
    appType: 2,
  },
  // 平台活动
  {
    id: 'seller-promotion-platform',
    title: '平台活动',
    name: 'seller-promotion-platform',
    path: '/seller/promotion/platform',
    level: 1,
    frontRoute: 'seller/promotion/platform',
    parentId: 'seller-promotion',
    sortOrder: 0,
    permission: '/seller/promotion/platform',
    icon: 'appstore',
    description: '平台活动',
    type: 0,
    appType: 2,
  },
  {
    id: 'seller-promotion-group',
    title: '拼团活动',
    name: 'seller-promotion-group',
    path: '/seller/promotion/group',
    level: 2,
    frontRoute: 'seller/promotion/group',
    parentId: 'seller-promotion-platform',
    sortOrder: 0,
    permission: '/seller/promotion/group',
    icon: 'team',
    description: '拼团活动',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-promotion-seckill',
    title: '秒杀活动',
    name: 'seller-promotion-seckill',
    path: '/seller/promotion/seckill',
    level: 2,
    frontRoute: 'seller/promotion/seckill',
    parentId: 'seller-promotion-platform',
    sortOrder: 1,
    permission: '/seller/promotion/seckill',
    icon: 'clock-circle',
    description: '秒杀活动',
    type: 1,
    appType: 2,
  },
  // 直播活动
  {
    id: 'seller-promotion-live',
    title: '直播活动',
    name: 'seller-promotion-live',
    path: '/seller/promotion/live',
    level: 1,
    frontRoute: 'seller/promotion/live',
    parentId: 'seller-promotion',
    sortOrder: 1,
    permission: '/seller/promotion/live',
    icon: 'video-camera',
    description: '直播活动',
    type: 0,
    appType: 2,
  },
  {
    id: 'seller-promotion-live-manage',
    title: '直播管理',
    name: 'seller-promotion-live-manage',
    path: '/seller/promotion/live-manage',
    level: 2,
    frontRoute: 'seller/promotion/live-manage',
    parentId: 'seller-promotion-live',
    sortOrder: 0,
    permission: '/seller/promotion/live-manage',
    icon: 'play-circle',
    description: '直播管理',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-promotion-live-goods',
    title: '直播商品',
    name: 'seller-promotion-live-goods',
    path: '/seller/promotion/live-goods',
    level: 2,
    frontRoute: 'seller/promotion/live-goods',
    parentId: 'seller-promotion-live',
    sortOrder: 1,
    permission: '/seller/promotion/live-goods',
    icon: 'shopping',
    description: '直播商品',
    type: 1,
    appType: 2,
  },
  // 商家活动
  {
    id: 'seller-promotion-shop',
    title: '商家活动',
    name: 'seller-promotion-shop',
    path: '/seller/promotion/shop',
    level: 1,
    frontRoute: 'seller/promotion/shop',
    parentId: 'seller-promotion',
    sortOrder: 2,
    permission: '/seller/promotion/shop',
    icon: 'shop',
    description: '商家活动',
    type: 0,
    appType: 2,
  },
  {
    id: 'seller-promotion-full',
    title: '满额活动',
    name: 'seller-promotion-full',
    path: '/seller/promotion/full',
    level: 2,
    frontRoute: 'seller/promotion/full',
    parentId: 'seller-promotion-shop',
    sortOrder: 0,
    permission: '/seller/promotion/full',
    icon: 'dollar',
    description: '满额活动',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-promotion-coupon',
    title: '优惠券',
    name: 'seller-promotion-coupon',
    path: '/seller/promotion/coupon',
    level: 2,
    frontRoute: 'seller/promotion/coupon',
    parentId: 'seller-promotion-shop',
    sortOrder: 1,
    permission: '/seller/promotion/coupon',
    icon: 'gift',
    description: '优惠券',
    type: 1,
    appType: 2,
  },
  // 分销管理
  {
    id: 'seller-promotion-distribution',
    title: '分销管理',
    name: 'seller-promotion-distribution',
    path: '/seller/promotion/distribution',
    level: 1,
    frontRoute: 'seller/promotion/distribution',
    parentId: 'seller-promotion',
    sortOrder: 3,
    permission: '/seller/promotion/distribution',
    icon: 'share-alt',
    description: '分销管理',
    type: 0,
    appType: 2,
  },
  {
    id: 'seller-promotion-distribution-goods',
    title: '分销商品',
    name: 'seller-promotion-distribution-goods',
    path: '/seller/promotion/distribution-goods',
    level: 2,
    frontRoute: 'seller/promotion/distribution-goods',
    parentId: 'seller-promotion-distribution',
    sortOrder: 0,
    permission: '/seller/promotion/distribution-goods',
    icon: 'shopping',
    description: '分销商品',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-promotion-distribution-order',
    title: '分销订单',
    name: 'seller-promotion-distribution-order',
    path: '/seller/promotion/distribution-order',
    level: 2,
    frontRoute: 'seller/promotion/distribution-order',
    parentId: 'seller-promotion-distribution',
    sortOrder: 1,
    permission: '/seller/promotion/distribution-order',
    icon: 'shopping-cart',
    description: '分销订单',
    type: 1,
    appType: 2,
  },

  // ========== 5. 统计 (statistics) ==========
  {
    id: 'seller-statistics',
    title: '统计',
    name: 'seller-statistics',
    path: '/seller/statistics',
    level: 0,
    frontRoute: 'seller/statistics',
    parentId: null,
    sortOrder: 5,
    permission: '',
    icon: 'bar-chart',
    description: '统计管理',
    type: 0,
    appType: 2,
  },
  // 统计管理
  {
    id: 'seller-statistics-management',
    title: '统计管理',
    name: 'seller-statistics-management',
    path: '/seller/statistics/management',
    level: 1,
    frontRoute: 'seller/statistics/management',
    parentId: 'seller-statistics',
    sortOrder: 0,
    permission: '/seller/statistics/management',
    icon: 'pie-chart',
    description: '统计管理',
    type: 0,
    appType: 2,
  },
  {
    id: 'seller-statistics-goods',
    title: '商品统计',
    name: 'seller-statistics-goods',
    path: '/seller/statistics/goods',
    level: 2,
    frontRoute: 'seller/statistics/goods',
    parentId: 'seller-statistics-management',
    sortOrder: 0,
    permission: '/seller/statistics/goods',
    icon: 'shopping',
    description: '商品统计',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-statistics-order',
    title: '订单统计',
    name: 'seller-statistics-order',
    path: '/seller/statistics/order',
    level: 2,
    frontRoute: 'seller/statistics/order',
    parentId: 'seller-statistics-management',
    sortOrder: 1,
    permission: '/seller/statistics/order',
    icon: 'shopping-cart',
    description: '订单统计',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-statistics-traffic',
    title: '流量统计',
    name: 'seller-statistics-traffic',
    path: '/seller/statistics/traffic',
    level: 2,
    frontRoute: 'seller/statistics/traffic',
    parentId: 'seller-statistics-management',
    sortOrder: 2,
    permission: '/seller/statistics/traffic',
    icon: 'line-chart',
    description: '流量统计',
    type: 1,
    appType: 2,
  },

  // ========== 6. 设置 (settings) ==========
  {
    id: 'seller-settings',
    title: '设置',
    name: 'seller-settings',
    path: '/seller/settings',
    level: 0,
    frontRoute: 'seller/settings',
    parentId: null,
    sortOrder: 6,
    permission: '',
    icon: 'setting',
    description: '系统设置',
    type: 0,
    appType: 2,
  },
  // 配送设置
  {
    id: 'seller-settings-shipment',
    title: '配送设置',
    name: 'seller-settings-shipment',
    path: '/seller/settings/shipment',
    level: 1,
    frontRoute: 'seller/settings/shipment',
    parentId: 'seller-settings',
    sortOrder: 0,
    permission: '/seller/settings/shipment',
    icon: 'car',
    description: '配送设置',
    type: 0,
    appType: 2,
  },
  {
    id: 'seller-settings-template',
    title: '配送模板',
    name: 'seller-settings-template',
    path: '/seller/settings/template',
    level: 2,
    frontRoute: 'seller/settings/template',
    parentId: 'seller-settings-shipment',
    sortOrder: 0,
    permission: '/seller/settings/template',
    icon: 'car',
    description: '配送模板',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-settings-logistics',
    title: '物流公司',
    name: 'seller-settings-logistics',
    path: '/seller/settings/logistics',
    level: 2,
    frontRoute: 'seller/settings/logistics',
    parentId: 'seller-settings-shipment',
    sortOrder: 1,
    permission: '/seller/settings/logistics',
    icon: 'truck',
    description: '物流公司',
    type: 1,
    appType: 2,
  },
  // 店铺管理
  {
    id: 'seller-settings-shop',
    title: '店铺管理',
    name: 'seller-settings-shop',
    path: '/seller/settings/shop',
    level: 1,
    frontRoute: 'seller/settings/shop',
    parentId: 'seller-settings',
    sortOrder: 1,
    permission: '/seller/settings/shop',
    icon: 'shop',
    description: '店铺管理',
    type: 0,
    appType: 2,
  },
  {
    id: 'seller-settings-shop-basic',
    title: '店铺设置',
    name: 'seller-settings-shop-basic',
    path: '/seller/settings/shop-basic',
    level: 2,
    frontRoute: 'seller/settings/shop-basic',
    parentId: 'seller-settings-shop',
    sortOrder: 0,
    permission: '/seller/settings/shop-basic',
    icon: 'setting',
    description: '店铺设置',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-settings-pickup',
    title: '自提管理',
    name: 'seller-settings-pickup',
    path: '/seller/settings/pickup',
    level: 2,
    frontRoute: 'seller/settings/pickup',
    parentId: 'seller-settings-shop',
    sortOrder: 1,
    permission: '/seller/settings/pickup',
    icon: 'shop',
    description: '自提管理',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-settings-pc',
    title: 'PC端',
    name: 'seller-settings-pc',
    path: '/seller/settings/pc',
    level: 2,
    frontRoute: 'seller/settings/pc',
    parentId: 'seller-settings-shop',
    sortOrder: 2,
    permission: '/seller/settings/pc',
    icon: 'desktop',
    description: 'PC端',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-settings-mobile',
    title: '移动端',
    name: 'seller-settings-mobile',
    path: '/seller/settings/mobile',
    level: 2,
    frontRoute: 'seller/settings/mobile',
    parentId: 'seller-settings-shop',
    sortOrder: 3,
    permission: '/seller/settings/mobile',
    icon: 'mobile',
    description: '移动端',
    type: 1,
    appType: 2,
  },
  // 店员设置
  {
    id: 'seller-settings-staff',
    title: '店员设置',
    name: 'seller-settings-staff',
    path: '/seller/settings/staff',
    level: 1,
    frontRoute: 'seller/settings/staff',
    parentId: 'seller-settings',
    sortOrder: 2,
    permission: '/seller/settings/staff',
    icon: 'team',
    description: '店员设置',
    type: 0,
    appType: 2,
  },
  {
    id: 'seller-settings-staff-manage',
    title: '店员管理',
    name: 'seller-settings-staff-manage',
    path: '/seller/settings/staff-manage',
    level: 2,
    frontRoute: 'seller/settings/staff-manage',
    parentId: 'seller-settings-staff',
    sortOrder: 0,
    permission: '/seller/settings/staff-manage',
    icon: 'user',
    description: '店员管理',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-settings-department',
    title: '部门管理',
    name: 'seller-settings-department',
    path: '/seller/settings/department',
    level: 2,
    frontRoute: 'seller/settings/department',
    parentId: 'seller-settings-staff',
    sortOrder: 1,
    permission: '/seller/settings/department',
    icon: 'apartment',
    description: '部门管理',
    type: 1,
    appType: 2,
  },
  {
    id: 'seller-settings-role',
    title: '角色权限',
    name: 'seller-settings-role',
    path: '/seller/settings/role',
    level: 2,
    frontRoute: 'seller/settings/role',
    parentId: 'seller-settings-staff',
    sortOrder: 2,
    permission: '/seller/settings/role',
    icon: 'safety',
    description: '角色权限',
    type: 1,
    appType: 2,
  },

  // ========== 7. 消息 (Main) ==========
  {
    id: 'seller-message',
    title: '消息',
    name: 'seller-message',
    path: '/seller/message',
    level: 0,
    frontRoute: 'seller/message',
    parentId: null,
    sortOrder: 7,
    permission: '',
    icon: 'message',
    description: '消息管理',
    type: 0,
    appType: 2,
  },
  // 系统消息
  {
    id: 'seller-message-system',
    title: '系统消息',
    name: 'seller-message-system',
    path: '/seller/message/system',
    level: 1,
    frontRoute: 'seller/message/system',
    parentId: 'seller-message',
    sortOrder: 0,
    permission: '/seller/message/system',
    icon: 'notification',
    description: '系统消息',
    type: 0,
    appType: 2,
  },
  {
    id: 'seller-message-system-manage',
    title: '系统消息',
    name: 'seller-message-system-manage',
    path: '/seller/message/system-manage',
    level: 2,
    frontRoute: 'seller/message/system-manage',
    parentId: 'seller-message-system',
    sortOrder: 0,
    permission: '/seller/message/system-manage',
    icon: 'message',
    description: '系统消息',
    type: 1,
    appType: 2,
  },
];
